apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          resources:
            requests:
              ephemeral-storage: "400Mi"
            limits:
              ephemeral-storage: "400Mi"
          image: chetan1111/blog:1.0.4
---
apiVersion: v1
kind: Service
metadata:
  name: blog-srv
spec:
  selector:
    app: blog
  ports:
    - name: blog
      protocol: TCP
      port: 4000
      targetPort: 4000
